const BASE = (import.meta.env.VITE_API_URL || 'http://localhost:5000/api').replace(/\/+$/, '');
const FALLBACK_MARKETS = [
  {id:'sehore',name:'Sehore Mandi',price:28,trend:'+4.2%',arrival:420,distance:32,transport:900,handling:220,demand:'High'},
  {id:'bhopal',name:'Bhopal Mandi',price:31,trend:'+2.8%',arrival:650,distance:58,transport:1550,handling:280,demand:'High'},
  {id:'indore',name:'Indore Mandi',price:34,trend:'+6.1%',arrival:900,distance:172,transport:3900,handling:350,demand:'Very high'},
  {id:'vidisha',name:'Vidisha Mandi',price:29,trend:'+1.4%',arrival:380,distance:72,transport:1900,handling:250,demand:'Medium'},
  {id:'dewas',name:'Dewas Mandi',price:33,trend:'+5.0%',arrival:520,distance:135,transport:3100,handling:320,demand:'High'}
];
const ORIGIN_DISTANCES:any={bhopal:{sehore:40,bhopal:8,indore:190,vidisha:60,dewas:170},indore:{sehore:175,bhopal:190,indore:8,vidisha:250,dewas:45},sehore:{sehore:8,bhopal:40,indore:175,vidisha:105,dewas:135},vidisha:{sehore:105,bhopal:60,indore:250,vidisha:8,dewas:205},dewas:{sehore:135,bhopal:170,indore:45,vidisha:205,dewas:8}};
function getUserId() { let id = localStorage.getItem('ks-user-id'); if (!id) { id = crypto.randomUUID(); localStorage.setItem('ks-user-id', id) } return id }
function applyLocation(items:any[],location:string){const key=Object.keys(ORIGIN_DISTANCES).find(k=>String(location||'').toLowerCase().includes(k));if(!key)return items;return items.map(m=>{const distance=ORIGIN_DISTANCES[key][m.id]??m.distance;const transport=Math.max(150,Math.round((distance/32)*m.transport));return {...m,distance,transport}})}
async function request<T>(path:string,options:RequestInit={}) { const controller=new AbortController(); const timer=window.setTimeout(()=>controller.abort(),3500); try { const res=await fetch(`${BASE}${path}`,{headers:{'Content-Type':'application/json','x-user-id':getUserId(),...(options.headers||{})},...options,signal:controller.signal}); if(!res.ok) throw new Error((await res.json().catch(()=>({}))).error||`Request failed: ${res.status}`); return res.json() as Promise<T>; } finally { window.clearTimeout(timer); } }
const fallbackBuyers=[{_id:'buyer1',name:'FreshHarvest Foods',offeredPrice:30,requirements:'Grade A · 1,000–5,000 kg',paymentReliability:98,verified:true,location:'Bhopal',transport:'Buyer arranged'},{_id:'buyer2',name:'MP Agro Processors',offeredPrice:29,requirements:'Grade A/B · 500–3,000 kg',paymentReliability:95,verified:true,location:'Indore',transport:'Shared'},{_id:'buyer3',name:'Central Retail Network',offeredPrice:31,requirements:'Grade A · 2,000+ kg',paymentReliability:97,verified:true,location:'Bhopal',transport:'Buyer arranged'},{_id:'buyer4',name:'LocalFresh Co.',offeredPrice:27,requirements:'Standard · 300–2,000 kg',paymentReliability:91,verified:true,location:'Sehore',transport:'Farmer arranged'}];
const fallbackOffers=[{_id:'offer1',lotId:'LOT-KS-0042',buyer:'FreshHarvest Foods',price:30,quantity:1000,status:'Pending',createdAt:new Date().toISOString()},{_id:'offer2',lotId:'LOT-KS-0038',buyer:'MP Agro Processors',price:29,quantity:800,status:'Accepted',createdAt:new Date().toISOString()}];
const fallbackTransactions=[{_id:'tx1',lotId:'LOT-KS-0042',buyer:'FreshHarvest Foods',amount:30000,status:'In transit',payment:'Pending',updatedAt:new Date().toISOString()}];
export const api = { health: () => request('/health'), markets: async (location='') => { try{return await request<any[]>(`/markets?location=${encodeURIComponent(location)}`)}catch{return applyLocation(FALLBACK_MARKETS,location)} }, recommendation: async (quantity:number,location='') => { try{return await request<any>(`/recommendation?quantity=${quantity}&location=${encodeURIComponent(location)}`)}catch{const q=Math.max(1,quantity||1000);const ranked=applyLocation(FALLBACK_MARKETS,location).map(m=>({...m,gross:m.price*q,net:m.price*q-m.transport-m.handling})).sort((a,b)=>b.net-a.net);return {best:ranked[0],markets:ranked,reasons:['Highest estimated net realization after transport and handling','Price trend is positive','Buyer demand is strong'],window:'Next 1–2 days'}} }, buyers: async () => {try{return await request<any[]>('/buyers')}catch{return fallbackBuyers}}, lots: () => request<any[]>('/lots'), createLot: (body:any) => request('/lots',{method:'POST',body:JSON.stringify(body)}), offers: async () => { try{return await request<any[]>('/offers')}catch{return fallbackOffers} }, offerStatus: async (id:string,status:string) => { try{return await request(`/offers/${id}/status`,{method:'POST',body:JSON.stringify({status})})}catch{const x=fallbackOffers.find(o=>o._id===id);if(x)x.status=status;return x||{_id:id,status}} }, transactions: async () => {try{return await request<any[]>('/transactions')}catch{return fallbackTransactions}}, notifications: () => request<any[]>('/notifications'), markNotificationRead: (id:string) => request(`/notifications/${id}/read`,{method:'PATCH'}), saveProfile: (body:any) => request('/profile',{method:'POST',body:JSON.stringify(body)}), profile: () => request<any>('/profile') };
