import {Router} from 'express';
import CropLot from '../models/CropLot.js'; import Buyer from '../models/Buyer.js'; import Offer from '../models/Offer.js'; import Transaction from '../models/Transaction.js'; import UserProfile from '../models/UserProfile.js';
const r=Router();
const markets=[{id:'sehore',name:'Sehore Mandi',price:28,trend:'+4.2%',arrival:420,distance:32,transport:900,handling:220,demand:'High'},{id:'bhopal',name:'Bhopal Mandi',price:31,trend:'+2.8%',arrival:650,distance:58,transport:1550,handling:280,demand:'High'},{id:'indore',name:'Indore Mandi',price:34,trend:'+6.1%',arrival:900,distance:172,transport:3900,handling:350,demand:'Very high'},{id:'vidisha',name:'Vidisha Mandi',price:29,trend:'+1.4%',arrival:380,distance:72,transport:1900,handling:250,demand:'Medium'},{id:'dewas',name:'Dewas Mandi',price:33,trend:'+5.0%',arrival:520,distance:135,transport:3100,handling:320,demand:'High'}];
const seedBuyers=[{_id:'buyer1',name:'FreshHarvest Foods',offeredPrice:30,requirements:'Grade A · 1,000–5,000 kg',paymentReliability:98,verified:true,location:'Bhopal',transport:'Buyer arranged'},{_id:'buyer2',name:'MP Agro Processors',offeredPrice:29,requirements:'Grade A/B · 500–3,000 kg',paymentReliability:95,verified:true,location:'Indore',transport:'Shared'},{_id:'buyer3',name:'Central Retail Network',offeredPrice:31,requirements:'Grade A · 2,000+ kg',paymentReliability:97,verified:true,location:'Bhopal',transport:'Buyer arranged'},{_id:'buyer4',name:'LocalFresh Co.',offeredPrice:27,requirements:'Standard · 300–2,000 kg',paymentReliability:91,verified:true,location:'Sehore',transport:'Farmer arranged'}];
let fallbackProfile:any=null;
let notices=[{id:'n1',title:'FreshHarvest Foods viewed your lot',text:'LOT-KS-0042 has a new buyer view.',type:'offer',read:false},{id:'n2',title:'Tomato prices increased',text:'Indore is up 6.1% today.',type:'price',read:false},{id:'n3',title:'Pickup scheduled',text:'Your Sehore pickup is scheduled for tomorrow.',type:'logistics',read:true}];
let fallbackOffers=[{_id:'offer1',lotId:'LOT-KS-0042',buyer:'FreshHarvest Foods',price:30,quantity:1000,status:'Pending',createdAt:new Date()},{_id:'offer2',lotId:'LOT-KS-0038',buyer:'MP Agro Processors',price:29,quantity:800,status:'Accepted',createdAt:new Date()}];
r.get('/health',(_,res)=>res.json({ok:true,service:'Krishi Setu API'}));
r.get('/markets',(_,res)=>res.json(markets));
r.get('/recommendation',(req,res)=>{const q=Math.max(1,Number(req.query.quantity)||1000); const ranked=markets.map(m=>({...m,gross:m.price*q,net:m.price*q-m.transport-m.handling})).sort((a,b)=>b.net-a.net); res.json({best:ranked[0],markets:ranked,reasons:['Highest estimated net realization after transport and handling','Price trend is positive','Buyer demand is strong'],window:'Next 1–2 days'});});
r.get('/buyers',async(_,res)=>{try{const db=await Buyer.find();res.json(db.length?db:seedBuyers)}catch{res.json(seedBuyers)}});
r.post('/lots',async(req,res)=>{try{const lot=await CropLot.create(req.body); notices.unshift({id:'n'+Date.now(),title:'Lot created successfully',text:`${req.body.crop||'Crop'} lot ${req.body.quantity||''} kg is ready for buyer matching.`,type:'lot',read:false});res.status(201).json(lot)}catch(e){res.status(400).json({error:'Unable to create lot'})}});
r.get('/lots',async(_,res)=>{try{res.json(await CropLot.find().sort({createdAt:-1}))}catch{res.json([])}});
r.get('/offers',async(_,res)=>{try{const db=await Offer.find().sort({createdAt:-1});res.json(db.length?db:fallbackOffers)}catch{res.json(fallbackOffers)}});
r.post('/offers/:id/status',async(req,res)=>{
  try{const x=await Offer.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true}); if(x){notices.unshift({id:'n'+Date.now(),title:`Offer ${req.body.status.toLowerCase()}`,text:'Your offer status has been updated.',type:'offer',read:false});return res.json(x)}}catch{}
  const fb=fallbackOffers.find(o=>o._id===req.params.id);
  if(fb){fb.status=req.body.status;notices.unshift({id:'n'+Date.now(),title:`Offer ${req.body.status.toLowerCase()}`,text:'Your offer status has been updated.',type:'offer',read:false});return res.json(fb)}
  res.json({ _id:req.params.id,status:req.body.status});
});
r.get('/transactions',async(_,res)=>{try{const db=await Transaction.find().sort({createdAt:-1});res.json(db.length?db:[{_id:'tx1',lotId:'LOT-KS-0042',buyer:'FreshHarvest Foods',amount:30000,status:'In transit',payment:'Pending',updatedAt:new Date()}])}catch{res.json([])}});
r.get('/notifications',(_,res)=>res.json(notices));
r.patch('/notifications/:id/read',(req,res)=>{const n=notices.find(x=>x.id===req.params.id);if(n)n.read=true;res.json(n||{})});
r.post('/profile',async(req,res)=>{const userId=String(req.header('x-user-id')||'demo-user');const body={...req.body,userId,quantity:Number(req.body.quantity)||0,storage:Boolean(req.body.storage)};try{const saved=await UserProfile.findOneAndUpdate({userId},body,{new:true,upsert:true,setDefaultsOnInsert:true});return res.json(saved)}catch{fallbackProfile={...body};return res.json(fallbackProfile)}}); r.get('/profile',async(req,res)=>{const userId=String(req.header('x-user-id')||'demo-user');try{const p=await UserProfile.findOne({userId}).lean();return res.json(p||{})}catch{return res.json(fallbackProfile||{})}});
export default r;